# Generated by Django 5.0.7 on 2024-07-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Subject')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('datetime_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
