# Generated by Django 5.0.6 on 2024-07-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_author_alter_blog_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(max_length=10000, verbose_name='Text'),
        ),
    ]
