# Generated by Django 5.0.7 on 2024-07-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=0, max_length=50, verbose_name='Author'),
            preserve_default=False,
        ),
    ]
