# Generated by Django 5.0.7 on 2024-07-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='source',
            field=models.CharField(default=0, max_length=100, verbose_name='Source'),
            preserve_default=False,
        ),
    ]
